# Generated by Django 2.1.1 on 2018-10-02 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180930_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 7, 34, 28, 669426, tzinfo=utc)),
        ),
    ]
